services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    develop:
      watch:
        - path: backend
          action: sync+restart
          target: /app
    ports:
      - "8000:8000"
