services:
  backend:
    extends:
      file: ./apps/backend/backend-compose.yaml
      service: backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    env_file: "./apps/backend/.env"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: "./apps/backend/.env"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongo_data:


networks:
  transparent-net:
    external: true
