[tools]
python = "3"
uv = "latest"

[tasks.start]
description = "start local dev environment"
run = "docker compose up --build -d"

[tasks.watch_app]
description = "activate compose watch mode/hot-reload"
run = "docker compose watch"

[tasks.destroy]
description = "destroy local dev environment"
run = "docker compose apps/down"

[tasks."ci:lint:backend"]
description = "run lint check on backend"
run = "uvx ruff check apps/backend"

[tasks."ci:unittest:backend"]
description = "run unit testing on backend"
run = "uvx pytest apps/backend"
