[tools]
python = "3"
uv = "latest"

[tasks.start]
description = "start local dev environment"
run = "docker-compose up --build --watch"

[tasks."ci:lint:backend"]
description = "run lint check on backend"
run = "uvx ruff check backend"

[tasks."ci:unittest:backend"]
description = "run unit testing on backend"
run = "uvx pytest backend"
