services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: transparent-backend
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app
    env_file: ".env"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USER: backend
      MONGODB_PASSWD: passwd
    ports:
      - "8000:8000"


