services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: transparent-backend
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app
    env_file: ".env"
    ports:
      - "8000:8000"
