name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build transparent backend docker image
      run: docker build apps/backend --file apps/backend/Dockerfile --tag transparent-backend:$(date +%s)
